twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'

    globals:
        app_actualSeason: '%env(APP_ACTUAL_SEASON)%'

    date:
        timezone: '%env(APP_TIMEZONE)%'

when@test:
    twig:
        strict_variables: true
