vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        profile_pictures:
            uri_prefix: /uploads/users
            upload_destination: '%kernel.project_dir%/public/uploads/users'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
