version: '3'

services:

    football_stats_app:
        container_name: football-stats-app
        build:
            context: ./docker
        volumes:
            - .:/var/www/html:rw
        depends_on:
            - football_stats_database
        extra_hosts:
            - "host.docker.internal:host-gateway"

    football_stats_database:
        container_name: football-stats-database
        image: mariadb:10.6
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mariadb-data:/var/lib/mysql

volumes:
    mariadb-data:

networks:
    default:
        driver: bridge
